### ISSUE TITLE
claude-3-opus-20240229 results

### ISSUE THREAD

**Issue by scf4** [evalplus/repoqa#36]
[opus-results.zip](https://github.com/evalplus/repoqa/files/15143478/opus-results.zip)
<img width="651" alt="Screenshot 2024-04-28 at 20 43 11" src="https://github.com/evalplus/repoqa/assets/768234/1e8c39ea-36c2-42eb-b61a-ea1799ccda8a">

**Comment by ganler** [comment]
Thank you @scf4! We just updated the leaderboard in the same time! Claude3 aced the retrieval task!

**Comment by ganler** [comment]
Check it out at https://evalplus.github.io/repoqa.html

**Comment by scf4** [comment]
Thanks, although our results are different (enough to overlap with Sonnet). Are you doing multiple runs per model?

**Comment by ganler** [comment]
Hi, I was doing greedy decoding (temp = 0). It can be possible that Claude controls some randomness.

**Comment by scf4** [comment]
Hey, yeah the OAI/Anthropic APIs have never been deterministic even with temperature of 0!
