### ISSUE TITLE
Use dynamic rope scaling by default for models with <=16k context length

### ISSUE THREAD

**Issue by ganler** [evalplus/repoqa#37]
Credit is given to @abacaj who shows that simple dynamic rope scaling can largely improve the performance of models trained using smaller contexts. (https://x.com/abacaj/status/1785147493728039111)

8k models to update using dynamic rope scaling:

- [x] [Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct)
- [x] [Meta-Llama-3-70B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct)
- [x] [codegemma-7b-it](https://huggingface.co/google/codegemma-7b-it)
- [x] [Qwen1.5-MoE-A2.7B](https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B)

**Comment by ganler** [comment]
Context: before that, the long context was "extended" by simply unlocking the "max_positional_embedding" which presents suboptimal performance.

**Comment by ganler** [comment]
It seems for CodeGemma-IT=7B there's not much improvements (actually a bit worse):

## (original) Vanilla context extension (simply remove the restriction of context size as if it can run longer context)

![image](https://github.com/evalplus/repoqa/assets/38074777/a7f53996-f3d4-4040-bf0d-1f79eca909b6)


## Context extension using dynamic rope scaling (scale factor =4 )

![image](https://github.com/evalplus/repoqa/assets/38074777/85657765-5e43-40b8-adfc-844af402c437)

**Comment by ganler** [comment]
Much better results for Llama3 8B:

## Vanilla

![image](https://github.com/evalplus/repoqa/assets/38074777/9732c549-7942-40d2-ba91-359512254bb6)

## Dynamic rope scaling

![image](https://github.com/evalplus/repoqa/assets/38074777/934214e8-276e-4999-8745-7713aea3e89c)

**Comment by ganler** [comment]
Per abacaj's suggestion, removing the first instruction part at https://github.com/evalplus/repoqa/blob/b07be70e270bee8895d701150418c5cfbe83e547/repoqa/search_needle_function.py#L25

seems to improve L3's performance. am re-running the L3 experiments.

**Comment by PengWenChen** [comment]
Hi @ganler
Thanks for sharing the experiment results of dynamic ntk with llama3.
I would like to ask what scaling_factor did you set for llama3 dynamic ntk?
Thank you!

**Comment by ganler** [comment]
4

**Comment by PengWenChen** [comment]
One more question
Did you change the numbers of rope_theta and max_positional_embedding?

**Comment by ganler** [comment]
No

**Comment by PengWenChen** [comment]
Thanks for your reply. :)
Did you have any suggestion about the value of this scaling factor in NTK or dynamic-NTK?
Currently, I tried the factor value empirically when meeting a new model which takes a lot of time...

**Comment by ganler** [comment]
I think for dynamic NTK it depends on the context you want: like llama3 has 8k ctx and you need 20k+ to do repoqa so it's natural to use a context size of 8x4 = 32k -- where `4` is the scaling factor. 

For other scaling methods I am not sure as it might even require some finetuning.
