### ISSUE TITLE
This test is heavily dependent on the code capability of the model ?

### ISSUE THREAD

**Issue by hijkzzz** [evalplus/repoqa#40]
I've noticed that some models perform well in text-based needle-in-haystack scenarios but not in this code test.

**Comment by ganler** [comment]
One major difference between SNF (search needle function) and the traditional needle test is that SNF requires the model to understand user description (aka advanced code search in software engineering) while a basic needle test only hopes the model to retrieve results from prefix. Mapping the description to corresponding code over a long context can be nontrivial even for humans.

**Comment by hijkzzz** [comment]
I got it, but this still requires the model to have a strong understanding of the code

**Comment by ganler** [comment]
Yes!
