### ISSUE TITLE
Discrepancies in Model Evaluation Results for Mistral-7B-Instruct-v0.2 and phi-3-mini-128-instruct

### ISSUE THREAD

**Issue by zyzzzz-123** [evalplus/repoqa#41]
Hi,

I recently explored your benchmark RepoQA, which I found to be excellent to evaluate the long-context code understanding capabilities of LLMs. Eager to test it myself, I conducted evaluations using the Mistral-7B-Instruct-v0.2 and phi-3-mini-128-instruct models. However, my results were different from those reported on your website and I noticed significant discrepancies between the hf-backend and vllm-backend.

Here are my results:

 **phi-3-mini-128-instruct**:
![image](https://github.com/evalplus/repoqa/assets/65536242/4c50591c-723e-4e84-a0e1-a5b764bae44e)
**Mistral-7B-Instruct-v0.2** :
![image](https://github.com/evalplus/repoqa/assets/65536242/1d4da0f1-bdf5-43c7-b83f-4af866fb29b4)

I just used these commands to install the environments and ran the experiments.
```
# without vLLM (can run openai, anthropic, and huggingface backends)
pip install --upgrade repoqa
# To enable vLLM
pip install --upgrade "repoqa[vllm]"
```
`repoqa.search_needle_function --model "Mistral-7B-Instruct-v0.2" --backend vllm --trust-remote-code`

Could you provide any insights into why there might be such differences in the results? Is there a possibility of environmental or configuration differences that could influence the outcomes?

Thank you for your assistance.

**Comment by scf4** [comment]
Possibly related https://github.com/vllm-project/vllm/issues/966

**Comment by ganler** [comment]
> hf results are worse than vLLM results

This one I don't have an immediate clue because I actually have not used HF to produce results so far. It could be a bug in the HF code.

> new vLLM results are better than the reported

One potential reason I guess the new results are better:

1. f0395c0f09f77c0edb6d9089e4852f3dea6a1b4a will cut model's response (only use the next model response as the output whereas initially, the output can include multi-turn response)
2. The post-processing of LLM response is still not perfect and multi-turn results will lead to a worse result. 

@JialeTomTian Let's optimize the post-processing here:

https://github.com/evalplus/repoqa/blob/1e97925deb8ee80247e2a989ba1e7c5c7ad22684/repoqa/compute_score.py#L64

1. Based on the model name, cut the response by the single-turn EOF (use `hacky_assistant_stop_seq`)
2. Recompute the scores of the results
3. Check if the new scores are better, if so make a PR.

**Comment by ganler** [comment]
@zyzzzz-123 Would be nice if you could compare our results.

We store all model outputs at: https://github.com/evalplus/repoqa/releases/download/dev-results/ntoken_16384-output.zip

If they share the same prefix then https://github.com/evalplus/repoqa/issues/41#issuecomment-2105576945 should be the direction.

Otherwise, it can be a problem of configurations.

**Comment by zyzzzz-123** [comment]
> This one I don't have an immediate clue because I actually have not used HF to produce results so far. It could be a bug in the HF code.


Could you possibly run any of these models on the HF backend? This would help me determine whether the issue is with the HF-backend code or if it's related to a configuration issue on my end.

> Would be nice if you could compare our results.
If they share the same prefix then https://github.com/evalplus/repoqa/issues/41#issuecomment-2105576945 should be the direction.

I'll proceed with this and update you as soon as I can.

**Comment by JialeTomTian** [comment]
> One potential reason I guess the new results are better:
> 
> https://github.com/evalplus/repoqa/commit/f0395c0f09f77c0edb6d9089e4852f3dea6a1b4a will cut model's response (only use the next model response as the output whereas initially, the output can include multi-turn response)
> The post-processing of LLM response is still not perfect and multi-turn results will lead to a worse result.

Applied post-processing by cutting the response by the single-turn EOF. The scores remained the same.

**Comment by zyzzzz-123** [comment]
@ganler Could you provide more details about the configuration issue? Are there any steps to diagnose it?

**Comment by ganler** [comment]
@zyzzzz-123  I used to run these models using:

1. Local `vllm` version `v0.4.1` and `v0.4.0`
2. `vllm`'s docker image for OpenAI-compatible service version `v0.4.1` and `v0.4.0`

**Comment by ganler** [comment]
It might be because of an update of the pre-processing cache. Let me re-run your models to confirm. But in general, I think higher scores are correct scores. (bugs should make things worse)

**Comment by ganler** [comment]
Am re-running phi-3 and mistral-7b-instruct-v0.2

**Comment by zyzzzz-123** [comment]
Much thanks to your prompt reply! 
And I will also rerun the experiments with ` vllmv4.0.0 ` to see whether it's the reason.

It would be so nice of you to run any model on **huggingface** backend as well. Because I got bad results on all models that I have tried, including `phi-3`, ` mistral-7b-instruct-v0.2`, `CodeLlama-7b-Instruct-hf`, `llama3`.

**Comment by ganler** [comment]
@zyzzzz-123 Thanks! Yeah, if you got bad results on HF that must be a bug. So maybe please stick on vLLM backend. :)

I created #42 to track that but it's gonna take a while to fix it. Or any contributions are welcome: HF code available at: https://github.com/evalplus/repoqa/blob/main/repoqa/provider/hf.py

**Comment by ganler** [comment]
Updated Phi-3 results:

<img width="761" alt="image" src="https://github.com/evalplus/repoqa/assets/38074777/81981920-b424-4b35-9f3d-186178c5bcde">

**Comment by ganler** [comment]
Updated mistral instruct-v0.2

<img width="907" alt="image" src="https://github.com/evalplus/repoqa/assets/38074777/c0795e75-13a5-46e0-a4d9-e0857d2f247d">

**Comment by ganler** [comment]
Using local vllm 0.4.2 on 2xA6000

**Comment by ganler** [comment]
@zyzzzz-123 Do you want to compare the model outputs between yours and ours as I suggested here? https://github.com/evalplus/repoqa/issues/41#issuecomment-2105577927

Any insights from the diff might be interesting.

**Comment by ganler** [comment]
BTW I am also using the latest commit which you can install via:

```
pip install --upgrade "repoqa[vllm] @ git+https://github.com/evalplus/repoqa@main
```

**Comment by ganler** [comment]
I found out why phi3 score is a bit low in the HEAD commit. In ab0ba02d505457128e4011e990521a5398e8a263 the regex pattern ask the output lines to start with "```" but phi3 likes adding a space ahead of it. 

So I fixed this by doing a `model_output.strip()` and the phi3 score looks much better:

<img width="708" alt="image" src="https://github.com/evalplus/repoqa/assets/38074777/dec3517e-d4e8-4f91-963a-61adff4c8e29">

966ff16375a84746ad91d69763d6b8aa69119f74

**Comment by ganler** [comment]
Same pattern for mistral models. They seem to produce spaces before "```" for some reasons.

**Comment by ganler** [comment]
Globally updated the leaderboard. https://evalplus.github.io/repoqa.html

**Comment by ganler** [comment]
Closing this issue as Huggingface results have been updated.
